# Generated by Django 4.1.2 on 2022-10-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                ("year_published", models.IntegerField(null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=3)),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
